version: 0.2

env:
  exported-variables:
    - ECR_REGION
    - ECR_REPOSITORY_NAME

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      - $(aws ecr get-login-password --region ${ECR_REGION} --no-include-email)
      - REPOSITORY_URI=${AWS_ACCOUNTID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}
      - echo ${REPOSITORY_URI}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - printf '{"AWSEBDockerrunVersion":"1","Image":{"Name":"%s","Update":"true"},"Ports":[{"ContainerPort":"3001"}]}' $REPOSITORY_URI:$IMAGE_TAG > Dockerrun.aws.json
  build:
    commands:
      - echo build started on `date`
      - echo Building the Docker image..
      - docker -v
      - docker build -t ${REPOSITORY_URI}:latest .
      - docker tag ${REPOSITORY_URI}:latest ${REPOSITORY_URI}:$IMAGE_TAG
      - docker tag ${REPOSITORY_URI}:latest ${REPOSITORY_URI}:sbx
  post_build:
    commands:
      - echo build completed on `date`
      - echo Pushing the Docker images...
      - docker push ${REPOSITORY_URI}:latest
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${REPOSITORY_URI}:sbx
artifacts:
  files:
    - Dockerrun.aws.json
