export const PRODUCT_COLL = 'v2_products';
export const PRODUCT_MODEL_NAME = 'v2/v2_products';

export enum PRODUCT_TYPE {
  ADDER = 'ADDER',
  ANCILLARY_EQUIPMENT = 'ANCILLARY_EQUIPMENT',
  BALANCE_OF_SYSTEM = 'BALANCE_OF_SYSTEM',
  BATTERY = 'BATTERY',
  INVERTER = 'INVERTER',
  MODULE = 'MODULE',
}

export enum PRICING_UNIT {
  PER_EACH = 'PER_EACH',
  PER_SOLAR_WATT = 'PER_SOLAR_WATT',
  PER_SOLAR_KILOWATT = 'PER_SOLAR_KILOWATT',
  PER_STORAGE_KILOWATT = 'PER_STORAGE_KILOWATT',
  PER_STORAGE_KILOWATT_HOUR = 'PER_STORAGE_KILOWATT_HOUR',
}

export enum COMPONENT_TYPE {
  INVERTER = 'INVERTER',
  SOLAR = 'SOLAR',
  STORAGE = 'STORAGE',
}

export enum BATTERY_TYPE {
  AC = 'AC',
  DC = 'DC',
}

export enum INVERTER_TYPE {
  MICRO = 'MICRO',
  STRING = 'STRING',
}
