export enum CONTRACT_TYPE {
  PRIMARY_CONTRACT = 'PRIMARY_CONTRACT',
  GRID_SERVICES_AGREEMENT = 'GRID_SERVICES_AGREEMENT',
  CHANGE_ORDER = 'CHANGE_ORDER',
  NO_COST_CHANGE_ORDER = 'NO_COST_CHANGE_ORDER',
}

export enum SIGN_STATUS {
  SENT = 'SENT',
  SIGNED = 'SIGNED',
}

export enum PROCESS_STATUS {
  INITIATED = 'INITIATED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR',
  DRAFT = 'DRAFT',
}

export enum REQUEST_MODE {
  ADD = 'ADD',
  UPDATE = 'UPDATE',
}

export const KEYS = {
  CONTRACT_TYPE: Symbol.for('contractType'),
};

export const CONTRACT_SECRET_PREFIX = 'contract';
