export enum CONTRACT_TYPE {
  PRIMARY = 'PRIMARY',
  CHANGE_ORDER = 'CHANGE_ORDER',
}

export enum SIGN_STATUS {
  SENT = 'SENT',
  SIGNED = 'SIGNED',
}

export enum PROCESS_STATUS {
  INITIATED = 'INITIATED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  ERROR = 'ERROR',
}

export enum REQUEST_MODE {
  ADD = 'ADD',
  UPDATE = 'UPDATE',
}
