name: Deploy
run-name: Deploy to ${{ inputs.env }}
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      folder:
        description: Folder
        required: true
        type: string
        default: .
      env:
        description: 'Environment'
        required: true
        type: choice
        options:
          - Production
          - Demo
        default: Demo
jobs: 
  deploy:
    uses: SwellEnergy/actions/.github/workflows/backend.yaml@development
    with:
      Environment:                   ${{ inputs.env }}
    permissions:
      id-token: write
      contents: read