name: Deploy
run-name: Deploy 
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs: 
  deploy_prod:
    uses: SwellEnergy/actions/.github/workflows/backend.yaml@development
    with:
      Environment:      Production
      SWL_PROCESS_ID:   wave-quote-service
    permissions:
      id-token: write
      contents: read
  deploy_demo:
    uses: SwellEnergy/actions/.github/workflows/backend.yaml@development
    with:
      Environment:      Demo
      SWL_PROCESS_ID:   wave-quote-service
    permissions:
      id-token: write
      contents: read