name: QA 
on:
  push:
    branches:
      - qa
  workflow_dispatch:
jobs: 
  deploy_qa:
    uses: SwellEnergy/actions/.github/workflows/backend.yaml@development
    with:
      Environment:      QA
    permissions:
      id-token: write
      contents: read