name: Deploy
run-name: Deploy 
on:
  push:
    branches:
      - uat
  workflow_dispatch:
jobs: 
  deploy_uat:
    uses: SwellEnergy/actions/.github/workflows/backend.yaml@development
    with:
      Environment: UAT
    permissions:
      id-token: write
      contents: read